---
- name: Validate required vars
  ansible.builtin.include_tasks: validate.yml

- name: Include OS setup tasks
  ansible.builtin.import_tasks: ensure-directories.yml

- name: Render Wi-Fi config
  ansible.builtin.include_tasks: generate-config-files.yml
