---
- name: Validate required variables
  ansible.builtin.assert:
    that:
      - wifi.ssid is defined
      - wifi.psk is defined
      - wifi.password is defined
      - hostname is defined
    fail_msg: "Missing required vars: wifi_ssid, wifi_psk, or hostname."
